CLASSES=\
	org.jinterop.dcom.common.IJIAuthInfo	\
	org.jinterop.dcom.common.IJICOMRuntimeWorker	\
	org.jinterop.dcom.common.IJIUnreferenced	\
	org.jinterop.dcom.common.JIComVersion	\
	org.jinterop.dcom.common.JIDefaultAuthInfoImpl	\
	org.jinterop.dcom.common.JIErrorCodes	\
	org.jinterop.dcom.common.JIException	\
	org.jinterop.dcom.common.JIRuntimeException	\
	org.jinterop.dcom.common.JISystem	\
	org.jinterop.dcom.core.IJIComObject	\
	org.jinterop.dcom.core.IJIUnsigned	\
	org.jinterop.dcom.core.JIArray	\
	org.jinterop.dcom.core.JICallBuilder	\
	org.jinterop.dcom.core.JIClsid	\
	org.jinterop.dcom.core.JIComObjectImpl	\
	org.jinterop.dcom.core.JIComObjectImplWrapper	\
	org.jinterop.dcom.core.JIComOxidDetails	\
	org.jinterop.dcom.core.JIComOxidRuntime	\
	org.jinterop.dcom.core.JIComOxidRuntimeHelper	\
	org.jinterop.dcom.core.JIComOxidStub	\
	org.jinterop.dcom.core.JIComServer	\
	org.jinterop.dcom.core.JICurrency	\
	org.jinterop.dcom.core.JIDualStringArray	\
	org.jinterop.dcom.core.JIFlags	\
	org.jinterop.dcom.core.JIFrameworkHelper	\
	org.jinterop.dcom.core.JIInterfacePointer	\
	org.jinterop.dcom.core.JILocalCoClass	\
	org.jinterop.dcom.core.JILocalInterfaceDefinition	\
	org.jinterop.dcom.core.JILocalMethodDescriptor	\
	org.jinterop.dcom.core.JILocalParamsDescriptor	\
	org.jinterop.dcom.core.JIMarshalUnMarshalHelper	\
	org.jinterop.dcom.core.JIObjectId	\
	org.jinterop.dcom.core.JIOrpcExtentArray	\
	org.jinterop.dcom.core.JIOrpcFlags	\
	org.jinterop.dcom.core.JIOrpcThat	\
	org.jinterop.dcom.core.JIOrpcThis	\
	org.jinterop.dcom.core.JIOxid	\
	org.jinterop.dcom.core.JIOxidResolver	\
	org.jinterop.dcom.core.JIPointer	\
	org.jinterop.dcom.core.JIProgId	\
	org.jinterop.dcom.core.JIRemActivation	\
	org.jinterop.dcom.core.JIRemUnknown	\
	org.jinterop.dcom.core.JIRemUnknownServer	\
	org.jinterop.dcom.core.JISecurityBinding	\
	org.jinterop.dcom.core.JISession	\
	org.jinterop.dcom.core.JISetId	\
	org.jinterop.dcom.core.JIStdObjRef	\
	org.jinterop.dcom.core.JIString	\
	org.jinterop.dcom.core.JIStringBinding	\
	org.jinterop.dcom.core.JIStruct	\
	org.jinterop.dcom.core.JIUnion	\
	org.jinterop.dcom.core.JIUnsignedByte	\
	org.jinterop.dcom.core.JIUnsignedFactory	\
	org.jinterop.dcom.core.JIUnsignedInteger	\
	org.jinterop.dcom.core.JIUnsignedShort	\
	org.jinterop.dcom.core.JIUserCallBuilder	\
	org.jinterop.dcom.core.JIVariant	\
	org.jinterop.dcom.impls.automation.ArrayDesc	\
	org.jinterop.dcom.impls.automation.CallConv	\
	org.jinterop.dcom.impls.automation.ElemDesc	\
	org.jinterop.dcom.impls.automation.FuncDesc	\
	org.jinterop.dcom.impls.automation.FuncKind	\
	org.jinterop.dcom.impls.automation.IdlDesc	\
	org.jinterop.dcom.impls.automation.IJIDispatch	\
	org.jinterop.dcom.impls.automation.IJIEnumVariant	\
	org.jinterop.dcom.impls.automation.IJITypeInfo	\
	org.jinterop.dcom.impls.automation.IJITypeLib	\
	org.jinterop.dcom.impls.automation.ImplTypeFlags	\
	org.jinterop.dcom.impls.automation.Internal_JIAutomationFactory	\
	org.jinterop.dcom.impls.automation.InvokeKind	\
	org.jinterop.dcom.impls.automation.JIAutomationException	\
	org.jinterop.dcom.impls.automation.JIDispatchImpl	\
	org.jinterop.dcom.impls.automation.JIEnumVARIANTImpl	\
	org.jinterop.dcom.impls.automation.JIExcepInfo	\
	org.jinterop.dcom.impls.automation.JITypeInfoImpl	\
	org.jinterop.dcom.impls.automation.JITypeLibImpl	\
	org.jinterop.dcom.impls.automation.ParamDesc	\
	org.jinterop.dcom.impls.automation.SafeArrayBounds	\
	org.jinterop.dcom.impls.automation.TypeAttr	\
	org.jinterop.dcom.impls.automation.TypeDesc	\
	org.jinterop.dcom.impls.automation.TypeKind	\
	org.jinterop.dcom.impls.automation.VarDesc	\
	org.jinterop.dcom.impls.JIObjectFactory	\
	org.jinterop.dcom.test.Driver	\
	org.jinterop.dcom.test.DWebBrowserEvents2	\
	org.jinterop.dcom.test.EventNotificationListener	\
	org.jinterop.dcom.test.FirstContact	\
	org.jinterop.dcom.test.FirstContact_Stub	\
	org.jinterop.dcom.test.JIOPCEventSink	\
	org.jinterop.dcom.test.KainTest	\
	org.jinterop.dcom.test.Main	\
	org.jinterop.dcom.test.MetrikonOPC	\
	org.jinterop.dcom.test.MSADO	\
	org.jinterop.dcom.test.MSEnumVariant	\
	org.jinterop.dcom.test.MSExcel	\
	org.jinterop.dcom.test.MSExcel2	\
	org.jinterop.dcom.test.MSExcel2_Test	\
	org.jinterop.dcom.test.MSExcel3	\
	org.jinterop.dcom.test.MSInternetExplorer	\
	org.jinterop.dcom.test.MSOutLookExpressContacts	\
	org.jinterop.dcom.test.MSPowerPoint	\
	org.jinterop.dcom.test.MSPowerPoint2	\
	org.jinterop.dcom.test.MSShell	\
	org.jinterop.dcom.test.MSSysInfo	\
	org.jinterop.dcom.test.MSTypeLibraryBrowser	\
	org.jinterop.dcom.test.MSTypeLibraryBrowser2	\
	org.jinterop.dcom.test.MSWMI	\
	org.jinterop.dcom.test.MSWMI2	\
	org.jinterop.dcom.test.MSWord	\
	org.jinterop.dcom.test.MSWord2	\
	org.jinterop.dcom.test.QtpComTest	\
	org.jinterop.dcom.test.SampleTestServer	\
	org.jinterop.dcom.test.SampleTestServerCallback	\
	org.jinterop.dcom.test.SysInfoEvents	\
	org.jinterop.dcom.test.Test	\
	org.jinterop.dcom.test.Test10KServer	\
	org.jinterop.dcom.test.TestCOMServer	\
	org.jinterop.dcom.test.TestJIThreading	\
	org.jinterop.dcom.test.TestWinNativeSSO	\
	org.jinterop.dcom.test.TestWinReg	\
	org.jinterop.dcom.test.Test_ITestServer2_Impl	\
	org.jinterop.dcom.test.WshShell	\
	org.jinterop.dcom.transport.JIComEndpoint	\
	org.jinterop.dcom.transport.JIComRuntimeConnectionContext	\
	org.jinterop.dcom.transport.JIComRuntimeEndpoint	\
	org.jinterop.dcom.transport.JIComRuntimeNTLMConnectionContext	\
	org.jinterop.dcom.transport.JIComRuntimeTransport	\
	org.jinterop.dcom.transport.JIComRuntimeTransportFactory	\
	org.jinterop.dcom.transport.JIComTransport	\
	org.jinterop.dcom.transport.JIComTransportFactory	\
	org.jinterop.dcom.transport.niosupport.ChannelListener	\
	org.jinterop.dcom.transport.niosupport.ChannelWrapper	\
	org.jinterop.dcom.transport.niosupport.ChannelWrapperFactory	\
	org.jinterop.dcom.transport.niosupport.ChannelWrapperImpl	\
	org.jinterop.dcom.transport.niosupport.SelectorManager	\
	org.jinterop.winreg.IJIWinReg	\
	org.jinterop.winreg.JIPolicyHandle	\
	org.jinterop.winreg.JIWinRegFactory	\
	org.jinterop.winreg.smb.JIWinRegStub
