CLASSES=\
	com.iwombat.foundation.Identifier	\
	com.iwombat.foundation.IdentifierFactory	\
	com.iwombat.foundation.uuid.UUID	\
	com.iwombat.foundation.uuid.UUIDFactory	\
	com.iwombat.util.GUIDUtil	\
	com.iwombat.util.HexStringUtil	\
	com.iwombat.util.StringUtil	\
	gnu.crypto.hash.BaseHash	\
	gnu.crypto.hash.IMessageDigest	\
	gnu.crypto.hash.MD4	\
	gnu.crypto.hash.MD5	\
	gnu.crypto.prng.ARCFour	\
	gnu.crypto.prng.BasePRNG	\
	gnu.crypto.prng.IRandom	\
	gnu.crypto.prng.LimitReachedException	\
	gnu.crypto.Registry	\
	gnu.crypto.util.Util	\
	ndr.Format	\
	ndr.NdrBuffer	\
	ndr.NdrException	\
	ndr.NdrObject	\
	ndr.NetworkDataRepresentation	\
	net.sourceforge.jtds.util.SSPIJNIClient	\
	rpc.BasicConnectionContext	\
	rpc.BindException	\
	rpc.Buffer	\
	rpc.Connection	\
	rpc.ConnectionContext	\
	rpc.ConnectionOrientedEndpoint	\
	rpc.ConnectionOrientedPdu	\
	rpc.core.AuthenticationVerifier	\
	rpc.core.ContextHandle	\
	rpc.core.InterfaceIdentifier	\
	rpc.core.Port	\
	rpc.core.PresentationContext	\
	rpc.core.PresentationResult	\
	rpc.core.PresentationSyntax	\
	rpc.core.ProtocolVersion	\
	rpc.core.UUID	\
	rpc.DefaultConnection	\
	rpc.Endpoint	\
	rpc.FaultCodes	\
	rpc.FaultException	\
	rpc.Fragmentable	\
	rpc.IntegrityException	\
	rpc.ncacn_np.RpcTransport	\
	rpc.ncacn_np.TransportFactory	\
	rpc.pdu.AlterContextPdu	\
	rpc.pdu.AlterContextResponsePdu	\
	rpc.pdu.Auth3Pdu	\
	rpc.pdu.BindAcknowledgePdu	\
	rpc.pdu.BindNoAcknowledgePdu	\
	rpc.pdu.BindPdu	\
	rpc.pdu.CancelCoPdu	\
	rpc.pdu.FaultCoPdu	\
	rpc.pdu.OrphanedPdu	\
	rpc.pdu.RequestCoPdu	\
	rpc.pdu.ResponseCoPdu	\
	rpc.pdu.ShutdownPdu	\
	rpc.PresentationException	\
	rpc.ProtocolDataUnit	\
	rpc.ProviderException	\
	rpc.RpcException	\
	rpc.security.ntlm.AuthenticationSource	\
	rpc.security.ntlm.Ntlm1	\
	rpc.security.ntlm.NtlmAuthentication	\
	rpc.security.ntlm.NtlmConnection	\
	rpc.security.ntlm.NtlmConnectionContext	\
	rpc.security.ntlm.NTLMKeyFactory	\
	rpc.security.ntlm.Responses	\
	rpc.Security	\
	rpc.Stub	\
	rpc.Transport	\
	rpc.TransportFactory
